apiVersion: v1
kind: Template
metadata:
  annotations:
    description: Secrets to support amq instance
    iconClass: icon-database
    tags: amq,activemq,secret
  creationTimestamp: null
  name: amq-secret
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    creationTimestamp: null
    name: ${APP_NAME}-amq-secret
  stringData:
    amq-password: ${AMQ_PASSWORD}
    amq-user: ${AMQ_USER}
  type: opaque
parameters:
- description: The name for the application.
  displayName: Application Name
  name: APP_NAME
  required: true
  value: broker
- description: User name for standard broker user.  It is required for connecting
    to the broker.  If left empty, it will be generated.
  displayName: A-MQ Username
  from: user[a-zA-Z0-9]{3}
  generate: expression
  name: AMQ_USER
- description: Password for standard broker user.  It is required for connecting to
    the broker.  If left empty, it will be generated.
  displayName: A-MQ Password
  from: '[a-zA-Z0-9]{8}'
  generate: expression
  name: AMQ_PASSWORD
