apiVersion: v1
kind: Template
metadata:
  annotations:
    description: Crunchy PostgreSQL Single Database using PVC
    iconClass: icon-database
    tags: database,postgresql,crunchy
  creationTimestamp: null
  name: crunchydata-single-master-minishift
objects:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      name: ${PG_SERVICE_NAME}
    name: ${PG_SERVICE_NAME}
  spec:
    ports:
    - nodePort: 0
      port: 5432
      protocol: TCP
      targetPort: 5432
    selector:
      app: ${PG_SERVICE_NAME}
      deploymentconfig: ${PG_SERVICE_NAME}
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: data-pvc
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 100Gi
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: backup-pvc
  spec:
    accessModes:
    - ReadOnlyMany
    resources:
      requests:
        storage: 1Gi
    selector:
      matchLabels:
        postgres: restore
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: pgconf-pvc
  spec:
    accessModes:
    - ReadOnlyMany
    resources:
      requests:
        storage: 1Gi
    selector:
      matchLabels:
        postgres: pgconf
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    labels:
      app: ${PG_SERVICE_NAME}
    name: ${PG_SERVICE_NAME}
  spec:
    replicas: 1
    selector:
      app: ${PG_SERVICE_NAME}
      deploymentconfig: ${PG_SERVICE_NAME}
    strategy:
      activeDeadlineSeconds: 864001
      recreateParams:
        timeoutSeconds: 864000
      resources: {}
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: ${PG_SERVICE_NAME}
          deploymentconfig: ${PG_SERVICE_NAME}
      spec:
        containers:
        - env:
          - name: PG_MODE
            value: master
          - name: PG_DATABASE
            value: ${PG_DATABASE}
          - name: PG_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                key: postgresql-root-password
                name: ${SECRET_NAME}
          - name: PG_MASTER_USER
            valueFrom:
              secretKeyRef:
                key: postgresql-master-user
                name: ${SECRET_NAME}
          - name: PG_MASTER_PASSWORD
            valueFrom:
              secretKeyRef:
                key: postgresql-master-password
                name: ${SECRET_NAME}
          - name: PG_USER
            valueFrom:
              secretKeyRef:
                key: postgresql-user-csv-list
                name: ${SECRET_NAME}
          - name: PG_PASSWORD
            valueFrom:
              secretKeyRef:
                key: postgresql-password-csv-list
                name: ${SECRET_NAME}
          - name: SHARED_BUFFERS
            value: 4096MB
          - name: BACKUP_PATH
            value: ${PG_RESTORE_PATH}
          image: crunchydata/crunchy-postgres:${CCP_IMAGE_TAG}
          name: ${PG_SERVICE_NAME}
          ports:
          - containerPort: 5432
            protocol: TCP
          readinessProbe:
            exec:
              command:
              - /usr/pgsql-9.5/bin/pg_isready
              - -Upostgres
              - -d${PG_DATABASE}
              - -h127.0.0.1
            initialDelaySeconds: 5
            periodSeconds: 5
          securityContext:
            capabilities: {}
          volumeMounts:
          - mountPath: /pgdata
            name: pgdata
            readOnly: false
          - mountPath: /pgconf
            name: pgconf
            readOnly: true
          - mountPath: /backup
            name: backup
            readOnly: true
        - env: []
          image: crunchydata/crunchy-pgbadger:${CCP_IMAGE_TAG}
          name: pg-badger
          ports:
          - containerPort: 15000
            protocol: TCP
          securityContext:
            capabilities: {}
          volumeMounts:
          - mountPath: /pgdata
            name: pgdata
            readOnly: true
        - env:
          - name: PG_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                key: postgresql-root-password
                name: ${SECRET_NAME}
          - name: PG_MASTER_USER
            valueFrom:
              secretKeyRef:
                key: postgresql-master-user
                name: ${SECRET_NAME}
          - name: PG_MASTER_PASSWORD
            valueFrom:
              secretKeyRef:
                key: postgresql-master-password
                name: ${SECRET_NAME}
          - name: PG_PORT
            value: "5432"
          - name: PROM_GATEWAY
            value: http://crunchy-promgateway:9091
          image: crunchydata/crunchy-collect:${CCP_IMAGE_TAG}
          name: collect
          volumeMounts:
          - mountPath: /pgdata
            name: pgdata
            readOnly: true
        securityContext:
          supplementalGroups:
          - 65534
        volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: ${PG_DATA_PVC_NAME}
        - name: pgconf
          persistentVolumeClaim:
            claimName: ${PG_PGCONF_PVC_NAME}
        - name: backup
          persistentVolumeClaim:
            claimName: ${PG_BACKUP_PVC_NAME}
    test: false
    triggers:
    - type: ConfigChange
  status: {}
parameters:
- description: The name to use for the service and container
  name: PG_SERVICE_NAME
  value: apname-db
- description: name of secret bundle
  name: SECRET_NAME
  value: qualifier-database-secret
- description: The image tag to pull with
  name: CCP_IMAGE_TAG
  value: centos7-9.5-1.4.1
- description: The image prefix to pull with
  name: CCP_IMAGE_PREFIX
  value: crunchydata
- description: The name of the database that will be created
  name: PG_DATABASE
  value: dbname
- description: The name for the pvc
  name: PG_DATA_PVC_NAME
  value: data-pvc
- description: The name for the pvc
  name: PG_PGCONF_PVC_NAME
  value: pgconf-pvc
- description: The name for the pvc
  name: PG_BACKUP_PVC_NAME
  value: backup-pvc
- description: Path to restore data, path is a relative offset from /backup mount point.
  name: PG_RESTORE_PATH
  value: minimal-2017-05-12-17-35-04


