apiVersion: v1
kind: Template
metadata:
  annotations:
    description: Secrets to support crunchy postgresql database
    iconClass: icon-database
    tags: database,secret,postgresql,crunchy
  creationTimestamp: null
  name: postgresql-secret
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    creationTimestamp: null
    name: ${SECRET_NAME}
  stringData:
    postgresql-application-admin-password: ${POSTGRESQL_APPLICATION_ADMIN_PASSWORD}
    postgresql-application-admin-user: ${POSTGRESQL_APPLICATION_ADMIN_USER}
    postgresql-master-password: ${POSTGRESQL_MASTER_PASSWORD}
    postgresql-master-user: ${POSTGRESQL_MASTER_USER}
    postgresql-password: ${POSTGRESQL_PASSWORD}
    postgresql-password-csv-list: ${POSTGRESQL_APPLICATION_ADMIN_PASSWORD},${POSTGRESQL_PASSWORD}
    postgresql-root-password: ${POSTGRESQL_ROOT_PASSWORD}
    postgresql-user: ${POSTGRESQL_USER}
    postgresql-user-csv-list: ${POSTGRESQL_APPLICATION_ADMIN_USER},${POSTGRESQL_USER}
  type: opaque
parameters:
- description: Qualifier string for application name.
  name: SECRET_NAME
  value: appname-secret
- description: PostgreSQL application username
  from: '[a-z]{12}'
  generate: expression
  name: POSTGRESQL_USER
- description: PostgreSQL application password
  from: '[a-zA-Z0-9]{12}'
  generate: expression
  name: POSTGRESQL_PASSWORD
- description: PostgreSQL root password
  from: '[a-zA-Z0-9]{12}'
  generate: expression
  name: POSTGRESQL_ROOT_PASSWORD
- description: PostgreSQL master user (often master)
  from: '[a-z]{12}'
  generate: expression
  name: POSTGRESQL_MASTER_USER
- description: PostgreSQL master password
  from: '[a-zA-Z0-9]{12}'
  generate: expression
  name: POSTGRESQL_MASTER_PASSWORD
- description: PostgreSQL application user with admin privs
  from: '[a-z]{12}'
  generate: expression
  name: POSTGRESQL_APPLICATION_ADMIN_USER
- description: PostgreSQL application admin password
  from: '[a-zA-Z0-9]{12}'
  generate: expression
  name: POSTGRESQL_APPLICATION_ADMIN_PASSWORD
